### ISSUE TITLE
Not compatible with werkzeug >= 3.0

### ISSUE THREAD

**Issue by s0undt3ch** [csernazs/pytest-httpserver#268]
```
[16:33:46] Traceback (most recent call last):
             File "/tmp/testing/artifacts/salt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
               return _run_code(code, main_globals, None,
             File "/tmp/testing/artifacts/salt/lib/python3.10/runpy.py", line 86, in _run_code
               exec(code, run_globals)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pytest/__main__.py", line 5, in <module>
               raise SystemExit(pytest.console_main())
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/_pytest/config/__init__.py", line 190, in console_main
               code = main()
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/_pytest/config/__init__.py", line 148, in main
               config = _prepareconfig(args, plugins)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
               config = pluginmanager.hook.pytest_cmdline_parse(
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
               return self._hookexec(self, self.get_hookimpls(), kwargs)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pluggy/manager.py", line 92, in _hookexec
               return self._inner_hookexec(hook, methods, kwargs)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pluggy/manager.py", line 83, in <lambda>
               self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
               gen.send(outcome)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
               config: Config = outcome.get_result()
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
               raise ex[1].with_traceback(ex[2])
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
               res = hook_impl.function(*args)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1058, in pytest_cmdline_parse
               self.parse(args)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1346, in parse
               self._preparse(args, addopts=addopts)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1229, in _preparse
               self.pluginmanager.load_setuptools_entrypoints("pytest11")
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pluggy/manager.py", line 297, in load_setuptools_entrypoints
               plugin = ep.load()
             File "/tmp/testing/artifacts/salt/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
               module = import_module(match.group('module'))
             File "/tmp/testing/artifacts/salt/lib/python3.10/importlib/__init__.py", line 126, in import_module
               return _bootstrap._gcd_import(name[level:], package, level)
             File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
             File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
             File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
             File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
             File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
             File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
             File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
             File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
               exec(co, module.__dict__)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pytest_httpserver/__init__.py", line 18, in <module>
               from .httpserver import HTTPServer
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
               exec(co, module.__dict__)
             File "/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/pytest_httpserver/httpserver.py", line 15, in <module>
               from werkzeug.http import parse_authorization_header
           ImportError: cannot import name 'parse_authorization_header' from 'werkzeug.http' (/tmp/testing/.nox/ci-test-onedir/lib/python3.10/site-packages/werkzeug/http.py)
```

**Comment by s0undt3ch** [comment]
Dam, you fixed this already.
Sorry for the noise.
